// <auto-generated />
using System;
using LojaDoSeuManoel.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LojaDoSeuManoel.Infrastructure.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250528234411_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LojaDoSeuManoel.Infrastructure.Data.Entities.CaixaUtilizadaPersistencia", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AlturaCaixaCm")
                        .HasColumnType("int");

                    b.Property<int>("ComprimentoCaixaCm")
                        .HasColumnType("int");

                    b.Property<int>("LarguraCaixaCm")
                        .HasColumnType("int");

                    b.Property<string>("NomeCaixa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("PedidoProcessadoId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("PedidoProcessadoId");

                    b.ToTable("CaixasUtilizadasNoPedido");
                });

            modelBuilder.Entity("LojaDoSeuManoel.Infrastructure.Data.Entities.PedidoProcessadoPersistencia", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DataRecepcao")
                        .HasColumnType("datetime2");

                    b.Property<string>("PedidoOriginalId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("PedidoOriginalId");

                    b.ToTable("PedidosProcessados");
                });

            modelBuilder.Entity("LojaDoSeuManoel.Infrastructure.Data.Entities.ProdutoEmCaixaPersistencia", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AlturaCm")
                        .HasColumnType("int");

                    b.Property<Guid>("CaixaUtilizadaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("ComprimentoCm")
                        .HasColumnType("int");

                    b.Property<int>("LarguraCm")
                        .HasColumnType("int");

                    b.Property<string>("ProdutoOriginalId")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CaixaUtilizadaId");

                    b.ToTable("ProdutosNaCaixa");
                });

            modelBuilder.Entity("LojaDoSeuManoel.Infrastructure.Data.Entities.TipoDeCaixaPersistencia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AlturaCm")
                        .HasColumnType("int");

                    b.Property<int>("ComprimentoCm")
                        .HasColumnType("int");

                    b.Property<int>("LarguraCm")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("VolumeCm3")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("TiposDeCaixa");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AlturaCm = 30,
                            ComprimentoCm = 80,
                            LarguraCm = 40,
                            Nome = "Caixa 1",
                            VolumeCm3 = 96000
                        },
                        new
                        {
                            Id = 2,
                            AlturaCm = 80,
                            ComprimentoCm = 40,
                            LarguraCm = 50,
                            Nome = "Caixa 2",
                            VolumeCm3 = 160000
                        },
                        new
                        {
                            Id = 3,
                            AlturaCm = 50,
                            ComprimentoCm = 60,
                            LarguraCm = 80,
                            Nome = "Caixa 3",
                            VolumeCm3 = 240000
                        });
                });

            modelBuilder.Entity("LojaDoSeuManoel.Infrastructure.Data.Entities.CaixaUtilizadaPersistencia", b =>
                {
                    b.HasOne("LojaDoSeuManoel.Infrastructure.Data.Entities.PedidoProcessadoPersistencia", "PedidoProcessado")
                        .WithMany("CaixasUtilizadas")
                        .HasForeignKey("PedidoProcessadoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PedidoProcessado");
                });

            modelBuilder.Entity("LojaDoSeuManoel.Infrastructure.Data.Entities.ProdutoEmCaixaPersistencia", b =>
                {
                    b.HasOne("LojaDoSeuManoel.Infrastructure.Data.Entities.CaixaUtilizadaPersistencia", "CaixaUtilizada")
                        .WithMany("ProdutosNaCaixa")
                        .HasForeignKey("CaixaUtilizadaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CaixaUtilizada");
                });

            modelBuilder.Entity("LojaDoSeuManoel.Infrastructure.Data.Entities.CaixaUtilizadaPersistencia", b =>
                {
                    b.Navigation("ProdutosNaCaixa");
                });

            modelBuilder.Entity("LojaDoSeuManoel.Infrastructure.Data.Entities.PedidoProcessadoPersistencia", b =>
                {
                    b.Navigation("CaixasUtilizadas");
                });
#pragma warning restore 612, 618
        }
    }
}
