version: '3.8'

services:
  loja-api:
    container_name: lojadoseumanoel-api
    build:
      context: .
      dockerfile: src/LojaDoSeuManoel.Api/Dockerfile
    ports:
      - "8088:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080
      - ConnectionStrings__DefaultConnection=Server=lojadb;Database=LojaDoSeuManoelDB_Docker;User ID=sa;Password=${SA_PASSWORD};TrustServerCertificate=True;MultipleActiveResultSets=true;
      - Authentication__Jwt__Key=${JWT_KEY}
      - Authentication__Jwt__Issuer=${JWT_ISSUER}
      - Authentication__Jwt__Audience=${JWT_AUDIENCE}
    depends_on:
      - lojadb
    networks:
      - lojanet

  lojadb:
    container_name: lojadoseumanoel-db
    image: "mcr.microsoft.com/mssql/server:2022-latest"
    ports:
      - "14333:1433"
    environment:
      SA_PASSWORD: "${SA_PASSWORD}"
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Developer"
    volumes:
      - lojadb_data:/var/opt/mssql
    networks:
      - lojanet

volumes:
  lojadb_data:

networks:
  lojanet:
    driver: bridge